apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "massbank-frontend.fullname" . }}-env-configmap
  labels:
    {{- include "massbank-frontend.labels" . | nindent 4 }}
data:
  MB3_API_URL: "https://{{ .Values.host }}/{{ .Values.pathPrefix }}-api"
  MB3_API_URL_INTERNAL: "http://{{ .Release.Name }}-massbank-api:8080/{{ .Values.pathPrefix }}-api"
  MB3_FRONTEND_URL: "https://{{ .Values.host }}"
  MB3_FRONTEND_BASE_URL: "/{{ .Values.pathPrefix }}"
  EXPORT_SERVICE_URL: "https://{{ .Values.host }}/{{ .Values.pathPrefix }}-export"
  EXPORT_SERVICE_URL_INTERNAL: "http://{{ .Release.Name }}-massbank-export-api:8080/{{ .Values.pathPrefix }}-export"
  HTML_HEAD_FILE: "{{ .Values.HTML_HEAD_FILE }}"
  HTML_BODY_FILE: "{{ .Values.HTML_BODY_FILE }}"
  DISTRIBUTOR_TEXT: "{{ .Values.DISTRIBUTOR_TEXT }}"
  DISTRIBUTOR_URL: "{{ .Values.DISTRIBUTOR_URL }}"
  MB3_FRONTEND_BROWSER_TAB_TITLE: "{{ .Values.MB3_FRONTEND_BROWSER_TAB_TITLE }}"
  MB3_FRONTEND_HOMEPAGE_INTRO_TEXT: "{{ .Values.MB3_FRONTEND_HOMEPAGE_INTRO_TEXT }}"
  MB3_FRONTEND_HOMEPAGE_NEWS_SECTION_TEXT: "{{ .Values.MB3_FRONTEND_HOMEPAGE_NEWS_SECTION_TEXT }}"
  MB3_FRONTEND_HOMEPAGE_FUNDING_SECTION_TEXT: "{{ .Values.MB3_FRONTEND_HOMEPAGE_FUNDING_SECTION_TEXT }}"
  MB3_FRONTEND_HOMEPAGE_ADDITIONAL_SECTION_NAME: "{{ .Values.MB3_FRONTEND_HOMEPAGE_ADDITIONAL_SECTION_NAME }}"
  MB3_FRONTEND_HOMEPAGE_ADDITIONAL_SECTION_TEXT: "{{ .Values.MB3_FRONTEND_HOMEPAGE_ADDITIONAL_SECTION_TEXT }}"