apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "massbank-dbtool.fullname" . }}
  labels:
    {{- include "massbank-dbtool.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "massbank-dbtool.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: {{ .Values.massbankReleaseName }}
              topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_PORT
              value: "5432"
            - name: DB_PASSWORD
              value: {{ .Values.password }}
            - name: DB_HOST
              value: {{ .Values.massbankReleaseName }}-postgresql
            - name: DB_NAME
              value: {{ .Values.database }}
            - name: DB_USER
              value: {{ .Values.username }}
            - name: MB_DB_INIT
              value: "true"
            {{- if not .Values.useSharedData }}
            - name: MB_GIT_REPO
              value: "https://github.com/MassBank/MassBank-data"
            - name: MB_GIT_BRANCH
              value: "main"
            - name: MB_DATA_DIRECTORY
              value: ""
            {{- else }}
            - name: MB_DATA_DIRECTORY
              value: "/MassBank-data"
            {{- end }}
            - name: MB_DROP_ALL
              value: "true"
          {{- if .Values.useSharedData }}
          volumeMounts:
            - name: massbank-data-volume
              mountPath: /MassBank-data
              readOnly: true
          {{- end }}
      {{- if .Values.useSharedData }}
      volumes:
        - name: massbank-data-volume
          persistentVolumeClaim:
            claimName: {{ .Values.sharedDataPvcName }}
      {{- end }}
