apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "massbank-api.fullname" . }}-env-configmap
  labels:
    {{- include "massbank-api.labels" . | nindent 4 }}
data:
  DB_PORT: "5432"
  DB_PASSWORD: "{{ .Values.password }}"
  DB_HOST: "{{ .Release.Name }}-postgresql"
  DB_NAME: "{{ .Values.massbankApiDatabase }}"
  DB_USER: "{{ .Values.username }}"
  MB3_SERVER_PORT: "8080"
  SIMILARITY_SERVICE_COSINE_URL: "http://{{ .Release.Name }}-massbank-similarity-api:8080/{{ .Values.pathPrefix }}-similarity"
  EXPORT_SERVICE_URL: "http://{{ .Release.Name }}-massbank-export-api:8080/{{ .Values.pathPrefix }}-export"
  MB3_API_URL: "https://{{ .Values.host }}"
  MB3_API_BASE_URL: "/{{ .Values.pathPrefix }}-api"

