apiVersion: v2
name: massbank-export-api
description: A Helm chart for massbank-export-api

type: application
version: 0.1.4
appVersion: "v2.3"

dependencies:
  - name: postgres
    version: 0.13.2
    repository: oci://registry-1.docker.io/cloudpirates
    condition: withPostgres
