apiVersion: v2
name: massbank-api
description: A Helm chart for massbank-api

type: application
version: 2025.12.3
appVersion: "v2025.10.4"

dependencies:
  - name: postgres
    version: 0.13.2
    repository: oci://registry-1.docker.io/cloudpirates
    condition: withPostgres