{{- if .Values.useSharedData }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "massbank-similarity-api.fullname" . }}-job-reader
  labels:
    {{- include "massbank-similarity-api.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "massbank-similarity-api.fullname" . }}-job-reader
  labels:
    {{- include "massbank-similarity-api.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "massbank-similarity-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "massbank-similarity-api.fullname" . }}-job-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}