name: Update Chart.yml Files to latest MassBank3 Version (Trigger)

on:
  repository_dispatch:
    types: [trigger-workflow]

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          ref: ${{ github.event.client_payload.sha }}

      - name: Extract version and save into Chart.yml files related to MassBank3
        run: |
          # Parse the version name from the payload
          version=${{ github.event.client_payload.version }}
          echo "Version: $version"
          # Run the update script with the extracted version
          bash ./.github/workflows/update.sh "$version"

      - name: Check for Changes
        id: check_changes
        run: |
          if [[ -n "$(git diff --exit-code)" ]]; then
            echo "Changes detected"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected -> no further action"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      # Commit and Push Changes if there are any
      - name: Commit Changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          # configure access to repository
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.ACTIONS_PAT }}@github.com/MassBank/MassBank-charts.git

          # stage file changes to be committed
          git add charts/massbank-api/Chart.yaml
          git add charts/massbank-frontend/Chart.yaml
          git add charts/massbank-dbtool/Chart.yaml

          # make commit with staged changes
          git commit -m 'chore: update to MassBank3 version ${{ github.event.client_payload.version }}'

          # push the commit back up to source GitHub repository
          git push -u origin main
